
-- To avoid losing any files, I will manually import the dataset instead of using the import wizard.

DROP TABLE beneficiaries;

CREATE TABLE beneficiaries (
    YEAR VARCHAR(50),
    MONTH VARCHAR(50),
    BENE_GEO_LVL VARCHAR(50),
    BENE_STATE_ABRVTN VARCHAR(50),
    BENE_STATE_DESC VARCHAR(50),
    BENE_COUNTY_DESC VARCHAR(50),
    BENE_FIPS_CD VARCHAR(50),
    TOT_BENES DOUBLE,
    ORGNL_MDCR_BENES DOUBLE,
    MA_AND_OTH_BENES DOUBLE,
    AGED_TOT_BENES DOUBLE,
    AGED_ESRD_BENES DOUBLE,
    AGED_NO_ESRD_BENES DOUBLE,
    DSBLD_TOT_BENES DOUBLE,
    DSBLD_ESRD_AND_ESRD_ONLY_BENES DOUBLE,
    DSBLD_NO_ESRD_BENES DOUBLE,
    MALE_TOT_BENES DOUBLE,
    FEMALE_TOT_BENES DOUBLE,
    WHITE_TOT_BENES DOUBLE,
    BLACK_TOT_BENES DOUBLE,
    API_TOT_BENES DOUBLE,
    HSPNC_TOT_BENES DOUBLE,
    NATIND_TOT_BENES DOUBLE,
    OTHR_TOT_BENES DOUBLE,
    AGE_LT_25_BENES DOUBLE,
    AGE_25_TO_44_BENES DOUBLE,
    AGE_45_TO_64_BENES DOUBLE,
    AGE_65_TO_69_BENES DOUBLE,
    AGE_70_TO_74_BENES DOUBLE,
    AGE_75_TO_79_BENES DOUBLE,
    AGE_80_TO_84_BENES DOUBLE,
    AGE_85_TO_89_BENES DOUBLE,
    AGE_90_TO_94_BENES DOUBLE,
    AGE_GT_94_BENES DOUBLE,
    DUAL_TOT_BENES DOUBLE,
    FULL_DUAL_TOT_BENES DOUBLE,
    PART_DUAL_TOT_BENES DOUBLE,
    NODUAL_TOT_BENES DOUBLE,
    QMB_ONLY_BENES DOUBLE,
    QMB_PLUS_BENES DOUBLE,
    SLMB_ONLY_BENES DOUBLE,
    SLMB_PLUS_BENES DOUBLE,
    QDWI_QI_BENES DOUBLE,
    OTHR_FULL_DUAL_MDCD_BENES DOUBLE,
    A_B_TOT_BENES DOUBLE,
    A_B_ORGNL_MDCR_BENES DOUBLE,
    A_B_MA_AND_OTH_BENES DOUBLE,
    A_TOT_BENES DOUBLE,
    A_ORGNL_MDCR_BENES DOUBLE,
    A_MA_AND_OTH_BENES DOUBLE,
    B_TOT_BENES DOUBLE,
    B_ORGNL_MDCR_BENES DOUBLE,
    B_MA_AND_OTH_BENES DOUBLE,
    PRSCRPTN_DRUG_TOT_BENES DOUBLE,
    PRSCRPTN_DRUG_PDP_BENES DOUBLE,
    PRSCRPTN_DRUG_MAPD_BENES DOUBLE,
    PRSCRPTN_DRUG_DEEMED_ELIGIBLE_FULL_LIS_BENES DOUBLE,
    PRSCRPTN_DRUG_FULL_LIS_BENES DOUBLE,
    PRSCRPTN_DRUG_PARTIAL_LIS_BENES DOUBLE,
    PRSCRPTN_DRUG_NO_LIS_BENES DOUBLE
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/beneficiaries.csv'
INTO TABLE beneficiaries
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM beneficiaries

-- Everything looks like it should.